// LOCALHOST
###
GET http://localhost:8080/contacts
# the request above returns a json object with contacts

###
GET http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d86
# returns single object id for carver

###
GET http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d87
# returns single object id for noah

###
GET http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d88
# returns single object id for dominc

###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Dr",
    "lastName": "Dunn",
    "email": "thedoctor@test.com",
    "favoriteColor": "red",
    "birthday": "07/23/00"
}
# post dr dunn

###
PUT http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d86 HTTP/1.1
Content-Type: application/json

{
    "firstName": "carver",
    "lastName": "fife",
    "email": "carvertheballer@test.com",
    "favoriteColor": "pink",
    "birthday": "07/21/02"
}
# edit carver

###
DELETE http://localhost:8080/contacts/63353a74f055794c3a06d9ff
# delete dr dunn



// PRODUCTION
###
GET https://personal-activity.onrender.com/contacts 
# returns a json object with contacts

###
GET https://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d86 
# returns single object id for carver

###
GET https://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d87
# returns single object id for noah

###
GET https://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d88
#returns single object id for dominic

###
POST http://personal-activity.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Dr",
    "lastName": "Dunn",
    "email": "thedoctor@test.com",
    "favoriteColor": "red",
    "birthday": "07/23/00"
}
# post dr dunn

###
PUT http://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d86 HTTP/1.1
Content-Type: application/json

{
    "firstName": "carver",
    "lastName": "fife",
    "email": "carvertheballer@test.com",
    "favoriteColor": "pink",
    "birthday": "07/21/02"
}
# edit carver

###
DELETE http://personal-activity.onrender.com/contacts/63353a74f055794c3a06d9ff
# delete dr dunn