// LOCALHOST
###
GET http://localhost:8080/contacts
# the request above returns a json object with all contacts

###
GET http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d86
# returns single object by id 

###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Emperor",
    "lastName": "Bird",
    "email": "theemperor@test.com",
    "favoriteColor": "white",
    "birthday": "07/23/97"
}
# post emperor bird

###
PUT http://localhost:8080/contacts/632c9c8c8d13bdbb2e6d5d86 HTTP/1.1
Content-Type: application/json

{
    "firstName": "carver",
    "lastName": "fife",
    "email": "carvertheballer@test.com",
    "favoriteColor": "orange",
    "birthday": "07/21/02"
}
# edit carver

###
DELETE http://localhost:8080/contacts/{:id}
# delete by id



// PRODUCTION
###
GET https://personal-activity.onrender.com/contacts 
# returns a json object with all contacts

###
GET https://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d86 
# returns single object by id 

###
POST http://personal-activity.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Emperor",
    "lastName": "Bird",
    "email": "theemperor@test.com",
    "favoriteColor": "white",
    "birthday": "07/23/97"
}
# post emperor bird

###
PUT http://personal-activity.onrender.com/contacts/632c9c8c8d13bdbb2e6d5d86 HTTP/1.1
Content-Type: application/json

{
    "firstName": "carver",
    "lastName": "fife",
    "email": "carvertheballer@test.com",
    "favoriteColor": "orange",
    "birthday": "07/21/02"
}
# edit carver

###
DELETE http://personal-activity.onrender.com/contacts/{:id}
# delete by id